### ISSUE TITLE
Не получается подключить виртуализацию

### ISSUE THREAD

**Issue by urii9158** [urii9158/Docker#1]
# Описание

Устанавливала Docker Desktop для Windows 10 22H2 x64

По инструкции подключения виртуализации BIOS требуется проверить, поддерживает ли система аппаратную виртуализацию.
Для этого в командной строке требуется ввести команду "systeminfo", и найти информацию про Hyper-V. 
Параметр Virtualization Enabled in Firmware должен означать, поддерживает ли система аппаратную виртуализацию или нет.
На скриншоте этот параметр не присутствует, поэтому я не могу понять, выполнять ли мне следующие шаги по подключению виртуализации BIOS.

Так же я пробовала ввести команду "docker compose up" в терминале. 

/см. скриншот

Может ли быть так, что компьютер не поддерживает виртуализацию, и мне стоит использовать виртуальную машину, предоставленную Нетологией? Я рассматривала это, меня сильно беспокоит ограничение во времени использования виртуальной машины...

Или может я пропустила какой-то шаг в установке, поэтому все остальное ломается?

# Скриншот

![Screenshot_14](https://github.com/user-attachments/assets/6e2546fe-553f-45d5-9271-21bcd5407591)
![Screenshot_15](https://github.com/user-attachments/assets/248c55ca-92a9-447e-a3f7-b20f41ca8109)
![Screenshot_16](https://github.com/user-attachments/assets/a0853b00-4751-4860-81d3-d72e11529d27)
![Screenshot_17](https://github.com/user-attachments/assets/e50a467d-8eff-4a46-ba73-d4f1cbc3a5db)

# Окружение

* **Операционная система:**  Windows 10 Pro 22H2 x64
* **IDE:** Intellij IDEA Community Edition 2023.3.4
* **Java:** OpenJDK 11
* **Исходник проекта:** netology.ru

**Comment by andrew-pahomov** [comment]
Для включения поддержки аппаратной виртуализации стоит пойти в биос компьютера и поискать там необходимые настройки. Если она не включена на уровне биоса, то Вы не сможете проверить её статус. Вы можете почитать например этот материал https://remontka.pro/enable-virtualization/ для более полного понимания процесса.  

Согласно приведенный логов можно сделать вывод о том, что движок докера не работает. В первую очередь надо проверить насколько ваша машина соответствует требованиям. После этого надо включить аппаратную поддержку виртуализации в биос и подсистему WSL2 в Windows. Все это я рассказывал на разборе.            

Если ваша машина не соответствует требованиям, то Вы можете получить доступ к виртуальной машине Нетологии, срок её использования можно будет продлить.

**Comment by urii9158** [comment]
Здравствуйте! Большое спасибо за помощь, смогла наконец нормально открыть BIOS.

В начале про BIOS я нашла лишь две строки : BIOS Information с пустым полем напротив, и BIOS Vendor.
После, по предоставленной инструкции я смогла найти Intel Virtulization Technology, напротив которой уже была настройка [Enabled], так что я не стала ничего менять и вышла из этого меню.

Проверила и перенастроила WSL2, убедилась, что в Docker Desktop горит зеленая плашка, и ввела "docker compose up" в терминале проекта, появилась новая ошибка :( 
Она немного отличается от той, что на лекции, так что я еще не пробовала те же действия для ее исправления.
Скриншот прикрепила к двум прошлым в Issue.

**Comment by andrew-pahomov** [comment]
Похожая проблема обсуждается в официальном форуме https://forums.docker.com/t/unauthorized-incorrect-username-or-password/35677/26, думаю вам может подойти решения из неё.

**Comment by urii9158** [comment]
Здравствуйте! После решения прошлой ошибки командой "docker login --username your_username_here" никаких дополнительных шагов не делала. Новая ошибка появилась после "docker compose up", скриншот прикрепила в issue.

Еще раз отмечу ветку на форуме https://forums.docker.com/t/error-response-from-daemon-open-pipe-docker-engine-windows-the-system-cannot-find-the-file-specified/131750, где предлагают переустановить Docker со снятием флажка «Использовать WSL 2 вместо Hyper-V (рекомендуется)», что не очень подходит под условия домашнего задания

**Comment by andrew-pahomov** [comment]
Вы можете использовать Hyper-V если готовы самостоятельно решать проблемы с его настройкой. Курс рассчитан на бэкенд WSL.

**Comment by andrew-pahomov** [comment]
Проблема с путями решения описана в обсуждении https://stackoverflow.com/questions/63330590/error-response-from-daemon-open-pipe-docker-engine-linux-the-system-cannot. Предлагаю использовать описанные рецепты.
